# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-30 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_role',
            field=models.TextField(default='EMPLOYEE'),
        ),
    ]
